name: Email Notification on Push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send email on push
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Cambios subidos a rama ${{ github.ref_name }}
          to: karen.guevara@iteso.mx, natalia.correa@iteso.mx
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Se han subido cambios a la rama: ${{ github.ref_name }}