name: Send main with push

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_mail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Cambios subidos a rama ${{ github.ref_name }}"
          body: "Se han subido cambios a la rama ${{ github.ref_name }}."
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
